[global]
showWarningOnDirectExecution = false
disableWidgetStateDuplicationWarning = true

[server]
port = 8558

[theme]
base = "dark"
backgroundColor = "black"
secondaryBackgroundColor = "grey"
textColor = "white"