[global]
showWarningOnDirectExecution = false
disableWidgetStateDuplicationWarning = true
runOnSave = true

[server]
port  = 801

[theme]
base = "dark"
backgroundColor = "black"
secondaryBackgroundColor = "grey"
textColor = "white"